### ISSUE TITLE
instructions

### ISSUE THREAD

**Issue by pikurasa** [abhijeetsingh0401/ABCLLM#1]
Your instructions on REAMDE.md say "pip install -r requirements.txt" but the file name is "requirement.txt".

**Comment by pikurasa** [comment]
This is what worked for me:

python -m venv myenv
source myenv/bin/activate
pip install -r requirement.txt

(At this point, I tried `python ollama.py`, but that didn't work until I did the following:)

pip install --upgrade langchain
pip install langchain-community langchain-core
pip install flask-cors
pip install --upgrade flask-cors

(And then I could successfully run the final python script)

python ollama.py

**Comment by abhijeetsingh0401** [comment]
Commit Resolve this 
https://github.com/abhijeetsingh0401/ABCLLM/commit/b6b6f7e35cce2dc14221719022acb9b44b9a592f
